#!/bin/bash

DEBIAN_FRONTEND=interactive

sudo apt install git=1:2.25.1-1ubuntu3.8 &> /dev/null

cp -r /srv/host/vm/secrets/.ssh /home/vagrant/

chmod 600 /home/vagrant/.ssh/id_*

ssh-keyscan github.com >> .ssh/known_hosts

cp -r /srv/host/vm/secrets/.gitconfig /home/vagrant/.gitconfig

# Clone the repository
#git -C /home/vagrant/repo/ pull


